version: 0.0
os: linux
files:
  -source: /
  destiniation: /home/ec2-user/express-app

hooks: 
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      rusas: ec2-user
  BeforeInstall: 
    - location: scripts/before-install.sh
      timeout: 300
      rusas: ec2-user
  ApplicationStart: 
    - location: scripts/application_start.sh
      timeout: 300
      rusas: ec2-user

