import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from 'react-bootstrap/Navbar'
import Nav from 'react-bootstrap/Nav'

import 'bootstrap/dist/css/bootstrap.min.css';
import { FormControl, Form, Card, Container, Button } from 'react-bootstrap'
import Col from 'react-bootstrap/Col'
import Row from 'react-bootstrap/Row'
import Carousel from 'react-bootstrap/Carousel'

import Dog1 from "../public/dog_1.jpg"
import Dog2 from "../public/dog_2.jpg"
import Dog3 from "../public/dog_3.png"
import Dog4 from "../public/dog_4.jpeg"
import Dog5 from "../public/dog_5.jpeg"
import Dog6 from "../public/dog_6.jpeg"
import Dog7 from "../public/dog_7.jpeg"
import Dog8 from "../public/dog_8.jpeg"
import Dog9 from "../public/dog_9.jpeg"
import Dog10 from "../public/dog_10.jpeg"


const inter = Inter({ subsets: ['latin'] })
export const getServerSideProps = async (ctx) => {
  
  const res = await fetch('http://localhost:4800/dogs/');

  ctx.res.setHeader(
    "Cache-Control",
    "public, s-maxage=10, stale-while-revalidate=59"
  );

  const data = await res.json();
  
  console.log(data.result)

  return {
    props: { dogs : data }
    
  }
  
}
export default function Home( {dogs} ) {
  return (
    
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
          <Navbar bg="dark" variant="dark">
          <Navbar.Brand href="/">Dog Transportation</Navbar.Brand>
            <Nav className="mr-auto">
              <Nav.Link href="/">Home</Nav.Link>
              <Nav.Link href="../register">Sign Up</Nav.Link>
              <Nav.Link href="../login" >Log In</Nav.Link>
              <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </Nav>     
          </Navbar>
        </nav>
      
      <main className={styles.main}>
        <div>
        <div className="Home">
          <Container>
            <Carousel>
              <Carousel.Item>
                <Image
                  className="d-block w-100"
                  src={Dog8}
                  alt="First slide"
                />
                <Carousel.Caption>
                  <h3>Dog Transport</h3>
                  <p>Help Dogs to Meet New Family</p>
                </Carousel.Caption>
              </Carousel.Item>
              <Carousel.Item>
                <Image
                  className="d-block w-100"
                  src={Dog9}
                  alt="Third slide"
                />

                <Carousel.Caption>
                  <h3>Travel with dogs</h3>
                  <p>Dogs Travel with You</p>
                </Carousel.Caption>
              </Carousel.Item>
              <Carousel.Item>
                <Image
                  className="d-block w-100"
                  src={Dog10}
                  alt="Third slide"
                />

                <Carousel.Caption>
                  <h3>Third slide label</h3>
                  <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                </Carousel.Caption>
              </Carousel.Item>
            </Carousel>



            <Form>
              <Row className="align-items-center">
                <Col xs= {5}>
                  <Form.Label htmlFor="inlineFormInput" srOnly>
                    Destination
                  </Form.Label>
                  
                    <Form.Control className="mb-2" type="text" placeholder="Destination" />
                
                </Col>

                <Col xs= {5}>
                  <Form.Label htmlFor="inlineFormInputGroup" srOnly>
                    Date
                  </Form.Label>
                  
                  
                    <Form.Control className="mb-2" type="date" id="start" name="trip-start" value="2021-01-22"
                    min="2021-01-01" max="2021-12-31" />
                  
                </Col>
                <Col xs= {2}>
                <button class="btn btn-success" type="submit">Search</button>
                </Col>
              </Row>
            </Form>
        
            <Row xs={2} md={2} className="g-4">
          
            {dogs.result && dogs.result.map(dog => 
               <div key={dog._id}>
                <Col>
                <Card>
                
                <Card.Img variant="top" src={" http://localhost:4800/" + dog.image } />
                  <Card.Body>
                    <Card.Title>{ dog.name }</Card.Title>
                    <Card.Text>
                    { dog.name } wants to go to { dog.airport }
                    </Card.Text>
                    <Button variant="primary">click for detail</Button>
                  </Card.Body>
                </Card>
              </Col>
              </div>
              )}

            </Row>
          </Container>
        </div>
      </div>
      </main>
    </>
  )
}
