import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Carousel, Form, Card, Container, Button, Nav, Navbar, Col, Row, NavDropdown } from 'react-bootstrap'
import { useAuth } from '../src/context/AuthContext'
import React, { useState } from 'react'
import { useRouter } from 'next/navigation'
import Dog8 from "../public/dog_8.jpeg"
import Dog9 from "../public/dog_9.jpeg"
import Dog10 from "../public/dog_10.jpeg"


const inter = Inter({ subsets: ['latin'] })
export const getServerSideProps = async (ctx) => {
  
  const res = await fetch('http://localhost:4800/dogs/');

  ctx.res.setHeader(
    "Cache-Control",
    "public, s-maxage=10, stale-while-revalidate=59"
  );

  const data = await res.json();
  
  console.log(data.result)

  return {

    props: { dogs : data }  

  }
  
}

export default function Home( {dogs} ) {
  const [ error, setError ] = useState('');
  const { currentUser, logOut } = useAuth();
  const router = useRouter();

  async function handleLogOut() {
  
    try {
  
      setError("")
      await logOut();
      console.log("you are logged out")
      return router.push("../login")
    } catch {
  
      setError("Failed to Log Out")
  
    }
  }

  return (
    
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar bg="dark" variant="dark">
            <Container fluid>
              <Navbar.Brand href="#home">Dog Transportation</Navbar.Brand>
              <Navbar.Toggle aria-controls="navbar-dark-example" />
              <Navbar.Collapse id="navbar-dark-example">
                <Nav>
                  <NavDropdown
                    id="nav-dropdown-dark-example"
                    title="Menu"
                    menuVariant="dark"
                    //className="ml-auto"
                  >
                    <NavDropdown.Item href="/">Home</NavDropdown.Item>
                    <NavDropdown.Item href="../mypage">My Page</NavDropdown.Item>
                    <NavDropdown.Item href="../register">Log out</NavDropdown.Item>
                    <NavDropdown.Divider />
                    <NavDropdown.Item href="../login" >Log In</NavDropdown.Item>
                  </NavDropdown>
                </Nav>
              </Navbar.Collapse>
              <Nav>
              <Nav.Item> 
                <Nav.Link href="../login">Log In</Nav.Link>
              </Nav.Item>
              </Nav>
          </Container>
        </Navbar>
      </nav>
      
      <main className={styles.main}>
        <div>
        <div className="Home">
          <Container>
            <Carousel>
              <Carousel.Item>
                <Image
                  style={{ height: '30rem'  }}
                  className="d-block w-100"
                  src={Dog8}
                  alt="First slide"
                />
                <Carousel.Caption>
                  <h3>Dog Transport</h3>
                  <p>Help Dogs to Meet New Family</p>
                </Carousel.Caption>
              </Carousel.Item>

              <Carousel.Item>
                <Image
                  style={{ height: '30rem'  }}
                  className="d-block w-100"
                  src={Dog9}
                  alt="Third slide"
                />
                <Carousel.Caption>
                  <h3>Travel with dogs</h3>
                  <p>Dogs Travel with You</p>
                </Carousel.Caption>
              </Carousel.Item>

              <Carousel.Item>
                <Image
                  style={{ height: '30rem'  }}
                  className="d-block w-100"
                  src={Dog10}
                  alt="Third slide"
                />
                <Carousel.Caption>
                  <h3>Third slide label</h3>
                  <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                </Carousel.Caption>
              </Carousel.Item>
            </Carousel>

            <Container>
            <Form>
              <Row className="align-items-center">
                <Col xs= {5}>
                  <Form.Label htmlFor="inlineFormInput" srOnly></Form.Label>
                  <Form.Control className="mb-2" type="text" placeholder="Destination" />
                </Col>

                <Col xs= {5}>
                  <Form.Label htmlFor="inlineFormInputGroup" srOnly></Form.Label>
                  <Form.Control className="mb-2" type="date" id="start" name="trip-start" value="2021-01-22"
                    min="2021-01-01" max="2021-12-31" />  
                </Col>

                <Col xs= {2}>
                <button class="btn btn-success" type="submit">Search</button>
                </Col>
              </Row>
            </Form>
            </Container>

            <Container className = "d-flex align-items-center justify-content-center" style = {{ minHeight: "100vh" }}>
              <Row xs={2} md={2} className="g-4">
                {dogs.result && dogs.result.map(dog => 
                  <div key={dog._id}>
                    <Col>
                      <Card style={{ width: '30rem', height: '30rem' }}>
                    
                        <Card.Img variant="top" style={{ width: '30rem', height: '20rem'  }} src={" http://localhost:4800/" + dog.image } />
                        <Card.Body>
                          <Card.Title>
                            { dog.name }
                          </Card.Title>
                          <Card.Text> 
                            { dog.name } wants to go to { dog.airport }
                          </Card.Text>
                          <Button variant="primary">click for detail</Button>
                        </Card.Body>
                      </Card>
                    </Col>
                  </div>
                )}
              </Row>
            </Container>
          </Container>
        </div>
      </div>
    </main>
  </>
  )
}
