import Head from 'next/head'
import React,  { useState, useEffect } from 'react';
import { Col, Row, Card, Navbar, Nav, Container, Offcanvas, Image } from 'react-bootstrap';
import Link from 'next/link'
//import { useRouter } from 'next/navigation'
import 'bootstrap/dist/css/bootstrap.min.css';
import { withProtected } from '../../src/app/routes';
import Stack from 'react-bootstrap/Stack';
import NavComp from "../../comps/NavComp.js";
import Map from "../../comps/map.js";
import { BsChatDots } from "react-icons/bs";
import "./mypage.css";




function myPage( {auth} ) {

  const { currentUser, logOut } = auth;
  const [ userInfo, setUserInfo ] = useState('');
  const [ dogs_resp, setFavDogs ] = useState("")
  const [ dogs, setDogs ] = useState("")
  
  console.log('currentUser', currentUser)
  console.log('image', currentUser.image)
  const loadUserInfo = async () => {
    const token = await currentUser.getIdToken();
    console.log(token)

  }


  

  const loadMyFavDogs = async () => {
    const cur_uid = currentUser.uid
    console.log('cuid', cur_uid)

    const res = JSON.parse(localStorage.getItem('userprofile')).result;
    console.log('res',res)
    const myData = res.filter(item => item.uid === cur_uid)[0]
    console.log(myData)
    if (myData != null) {
      const favDogs = myData.favorite
      console.log('fd',favDogs)

      const dogs_result = await JSON.parse(localStorage.getItem('dogs')).result
      
      console.log('resp',dogs_result)
      var dogs_resp = []

            for(var d in favDogs){
              console.log('d', favDogs[d])
              dogs_resp.push(dogs_result.filter(item => item._id === favDogs[d]));
              console.log(dogs_resp.flat())
            }
                
      setFavDogs(dogs_resp.flat())
    }
  }
  const loadMyDogs = async () => {
		const token = await currentUser.getIdToken();
		console.log(token)
		const cur_uid = currentUser.uid


		const res = await fetch('http://localhost:4800/users', {
  				headers: {authorization: `Bearer ${token}`}
		})
		const response = await res.json()
		console.log(response.result)
		const dogs = response.result.filter(item => item.uid === cur_uid )
		console.log(dogs)
		setDogs(dogs)
	  
	}
  useEffect(() => {
    
    if (currentUser) {
      loadUserInfo();
      loadMyFavDogs();
      loadMyDogs();
    }
  }, [currentUser]);
  
  console.log("mypage")
  console.log(currentUser)
  console.log('setdogs', dogs.length)

 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavComp />
      <Container style = {{ minHeight: "50vh" }}>

      <Stack direction="horizontal" gap={2}>
    
        <div className='myPageDisplayName' style = {{padding: 30, paddingBottom: 30, paddingTop: "5rem"}}>
          {!currentUser.photoURL?
          <Image
                style={{ height: '10rem'  }}
                className="d-block w-100"
                src="http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fdog_9.77c974bd.jpeg&w=640&q=75"
                roundedCircle 
              />: <Image
              style={{ height: '10rem'  }}
              className="d-block w-100"
              src="currentUser.files[0].name"
              roundedCircle 
            />}
          
        </div>
        <div>
          <h2> { currentUser && <div className = "username_profile" style= {{color: "#3A98B9", paddingBottom:"1rem"}}>{currentUser.displayName? currentUser.displayName: currentUser.email}'s page</div> } </h2>
          <Link href= {{
                            pathname: `../profile/${currentUser.uid}`,
                            query: {
                              uid: currentUser.uid
                            }// the data
                          }} >
              <button className='updateButton' >Update Profile</button>
            </Link>
        </div>
       
       </Stack>
      </Container>
    
      <Container style = {{ minHeight: "100vh" }}>
      <div className="mypage">
       
          <div className="favorites" > 
          <div className="fav_left">
          <h2>{ currentUser && <div className="username">{currentUser.displayName? currentUser.displayName: currentUser.email}'s favorites</div> } </h2>
          </div>
          <div className='fav_right'>
            <Row style = {{ display: "flex", flexWrap: "wrap", gap: "15px", paddingLeft:"6rem"}}>
              {dogs_resp? dogs_resp.map(dog => 
                <div key={dog._id} style = {{width: "fit-content"}}>
                    <Col style = {{width: "fit-content"}}>
                      <Card style={{ width: '20rem', height: '25rem' }}>
                      <Card.Img variant="top" style={{ width: '19.9rem', height: '15rem'  }} src={" http://localhost:4800/" + dog.image } />
                      <Card.Body>
                        <Card.Title>
                          { dog.name }   <a href={"../chatroom/" + currentUser.uid}><BsChatDots /></a>
                        </Card.Title>
                        <Card.Text> 
                          { dog.name } wants to go to { dog.airport }
                        </Card.Text>
                        <Link href={{
                            pathname: `../detail/${dog._id}`,
                            query: {
                              dog: dog._id
                            }// the data
                          }} >
                            <button className='detailButton'> click for detail</button>
                           
                        </Link>
                      </Card.Body>
                    </Card>
                  </Col>
                </div>
              ):<h3>add favorite dogs</h3> }
              </Row>
              </div>
            
          </div> 
          <div  className="myHomeNumMessage">
            <div className='message_left'>
              <div>
          <h2>{ currentUser && <div className="username" style = {{padding: 30, paddingBottom: 40 }}>{currentUser.displayName? currentUser.displayName: currentUser.email}'s messages</div> } </h2>
            <div style={{paddingLeft: "3.5rem"}}>
            <Link href= {{
                            pathname: `../chatroom/${currentUser.uid}`,
                            query: {
                              uid: currentUser.uid
                            }// the data
                          }}  >
              <button className='chatButton'> go to chatroom</button>
            </Link>
            </div>
            </div>
          </div>
          <div className='message_right' style={{paddingTop: "15rem"}}>
            <p>You have {length} new messages</p>
            
            </div>
          </div>

          <div className="myHomeNumDogs" style = {{padding: 50,  paddingTop: 10, paddingBottom: 40}}>
          <div className='numDog_left'>
          <h2> { currentUser && <div className="username" style = {{padding: 30, paddingTop: 20, paddingBottom: 40}}>{currentUser.displayName? currentUser.displayName: currentUser.email}'s dogs</div> } </h2>
       
          <div style={{paddingLeft: "3.5rem"}}>
            <Link href= {{
                            pathname: `../admin/${currentUser.uid}`,
                            query: {
                              uid: currentUser.uid
                            }// the data
                          }} >
             <button className='uploadButton' > upload more dogs</button>
            </Link>
          </div>
          </div>
            
          <div className='numDog_right'>
            <Container className = "d-flex align-items-center justify-content-center" style = {{ minHeight: "40vh" }}>
            {dogs.length === 0 && <p>You have {dogs.length} dogs</p>}
         
            <Row style = {{ display: "flex", flexWrap: "wrap", gap: "12px"}}>
                {dogs && dogs.map(dog => 
                  <div key={dog._id}  style = {{width: "fit-content"}}>
                    <Col  style = {{width: "fit-content"}}>
                      <Card style={{ width: '20rem', height: '25rem' }}>
                    
                        <Card.Img variant="top" style={{ width: '19.9rem', height: '15rem'  }} src={" http://localhost:4800/" + dog.image } />
                        <Card.Body>
                        	<Card.Title>
                            	{ dog.name }
                          	</Card.Title>
                          	<Card.Text> 
                            	{ dog.name } wants to go to { dog.airport }
                          	</Card.Text>
                          </Card.Body>
                        </Card>
                      </Col>
                    </div>
                  )}
          
                </Row>
              </Container>
              </div>
            </div>
        </div>
     </Container>
    </>
   
  )
}

export default withProtected(myPage)
