import Head from 'next/head'
import React,  { useState } from 'react';
import { Col, Row, Card, Alert, Navbar, Nav, NavDropdown, Container } from 'react-bootstrap';
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import 'bootstrap/dist/css/bootstrap.min.css';
import { withProtected } from '../../src/app/routes';


function myPage( {auth} ) {

  const [ error, setError ] = useState('')
  const { currentUser, logOut } = auth;
  const router = useRouter()

  async function handleLogOut() {
  
    try {

      setError("")
      await logOut();
    } catch {

      setError("Failed to Log Out")

    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar bg="dark" variant="dark">
            <Container fluid>
              <Navbar.Brand href="#home">Dog Transportation</Navbar.Brand>
              <Navbar.Toggle aria-controls="navbar-dark-example" />
              <Navbar.Collapse id="navbar-dark-example">
                <Nav>
                  <NavDropdown
                    id="nav-dropdown-dark-example"
                    title="Menu"
                    menuVariant="dark"
                    //className="ml-auto"
                  >
                    <NavDropdown.Item href="/">Home</NavDropdown.Item>
                    <NavDropdown.Item href="../mypage">My Page</NavDropdown.Item>
                    <NavDropdown.Item href="../register">Log out</NavDropdown.Item>
                    <NavDropdown.Divider />
                    <NavDropdown.Item href="../login" >Log In</NavDropdown.Item>
                  </NavDropdown>
                </Nav>
              </Navbar.Collapse>
              <Nav>
              <Nav.Item> 
                <Nav.Link onClick = { handleLogOut }>Log Out</Nav.Link>
              </Nav.Item>
              </Nav>
          </Container>
        </Navbar>
      </nav>
      <Container className = "d-flex align-items-center justify-content-center"
	style = {{ minHeight: "100vh" }}>
      <div className = "w-100" style = {{ maxWidth: '400px'}}>
      <Card>
        <Card.Body>
          <h2 className = "text-center mb-4">My Page</h2> 
          { error && <Alert variant = "danger"> { error } </Alert> }
          { currentUser && <div>Congratulations {currentUser?.email}! You are logged in.</div>}
          <Link href= "../admin" className="btn btn-primary w-100 mt-3">
            Upload Dogs  
          </Link>
        </Card.Body>
      </Card>  
      </div>
      </Container>  
    </>
   
  )
}

export default withProtected(myPage)
