import Head from 'next/head'
import React from "react";
import { useEffect, useState, useRef } from 'react';
import { useRouter } from "next/router";
import { Col, Row, Card, Image, Navbar, Nav, Form, Container, Offcanvas, Button } from 'react-bootstrap';
import Link from 'next/link'
import NavComp from "../../comps/NavComp.js";
import Map from "../../comps/map.js";
import 'bootstrap/dist/css/bootstrap.min.css';
import { withProtected } from '../../src/app/routes';
import FormControlLabel from "@mui/material/FormControlLabel";
import FavoriteIcon from "@mui/icons-material/Favorite";
import FavoriteBorderIcon from "@mui/icons-material/FavoriteBorder";
import Checkbox from "@mui/material/Checkbox";
import { GoogleMap, InfoWindowF, MarkerF, useJsApiLoader, useLoadScript } from "@react-google-maps/api"
import { BsChatDots } from "react-icons/bs";

//import { Field, Form, Formik } from "formik";
//import * as Yup from 'yup';

export const DEFAULT_DISTANCE_IN_KM = "1000"

function detail({ auth }) {
	const [ error, setError ] = useState('')
	const router = useRouter()
	//const [ dog, setDog ] = useState("")
	const [show, setShow] = useState(false);
 	const [target, setTarget] = useState(null);
  	const ref = useRef(null);
	const { currentUser, logOut } = auth;
	 const [isLoading, setLoading] = useState(false); 
	//const handleClick = () => setLoading(true);
	
  	console.log('query',router.query); 

  	const { dog } = router.query; 
	console.log('dog_id', dog)

	const dogs = JSON.parse(localStorage.getItem('dogs'));
	const thisdog = dogs.result.filter(item => item._id === dog)[0];
	console.log('ddd', dogs)
	console.log('this', thisdog)

	const { isLoaded, loadError } = useLoadScript({
		
		googleMapsApiKey: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
		
	})
	if (loadError) {
		console.log("Map cannot be loaded right now, sorry.")
	  }


	async function handleLogOut() {
	
	  try {
  
		setError("")
		await logOut();
	  } catch {
  
		setError("Failed to Log Out")
  
	  }
	}

	return (
	  <>
		<Head>
		  <title>Create Next App</title>
		  <meta name="description" content="Generated by create next app" />
		  <meta name="viewport" content="width=device-width, initial-scale=1" />
		  <link rel="icon" href="/favicon.ico" />
		</Head>
		<NavComp />
		<div classNmae = "dogname-detail" style = {{color: "#3A98B9", paddingTop: "2rem",  paddingLeft: "30px", fontSize: "40px"}}>
		 About {thisdog.name} 
		 </div>
		 <Container className = "d-flex align-items-center justify-content-center" style = {{ minHeight: "100vh" }}>
			
			<Card style={{ width: '60rem', height:'40rem'}}>
				<Card.Body>
					<Row>
						<Col>
							<Image variant="left" src={"http://localhost:4800/"+ thisdog.image} roundedCircle
							style={{ width: '26rem', height:'25rem'}}/>
								
							<Card.Text style={{paddingTop:"2rem", color: "#3A98B9", fontSize:"20px"}} >
							<a><BsChatDots /></a>
							<Card.Link href={"../chatroom/" + currentUser.uid}>send message</Card.Link>
							<div className="detailMessage" >{thisdog.message}</div>
							</Card.Text>
						</Col>
						<Col>
						 
							{!isLoaded? <div>Loading...</div>: <div><Map location={[ 40,  -73.9 ]} /></div>}
							
						</Col>
					</Row>	
				</Card.Body>
			</Card>	 	  
        </Container>		
	  </> 
	)
  }
  
  export default withProtected(detail)
  