import Head from 'next/head'
import React from "react";
import { useEffect, useState, useRef } from 'react';
import { useRouter } from "next/router";
import { Col, Row, Card, Image, Navbar, Nav, Form, Container, Offcanvas, Button } from 'react-bootstrap';
import Link from 'next/link'
import NavComp from "../../comps/NavComp.js";
import 'bootstrap/dist/css/bootstrap.min.css';
import { withProtected } from '../../src/app/routes';
import Overlay from 'react-bootstrap/Overlay';
import Popover from 'react-bootstrap/Popover';
import FormControlLabel from "@mui/material/FormControlLabel";
import FavoriteIcon from "@mui/icons-material/Favorite";
import FavoriteBorderIcon from "@mui/icons-material/FavoriteBorder";
import Checkbox from "@mui/material/Checkbox";
import { GoogleMap, InfoWindowF, MarkerF, useJsApiLoader } from "@react-google-maps/api"

//import { Field, Form, Formik } from "formik";
//import * as Yup from 'yup';

export const DEFAULT_DISTANCE_IN_KM = "1000"

function detail({ auth }) {
	const [ error, setError ] = useState('')
	const router = useRouter()
	//const [ dog, setDog ] = useState("")
	const [show, setShow] = useState(false);
 	const [target, setTarget] = useState(null);
  	const ref = useRef(null);
	const { currentUser, logOut } = auth;
	//const [isLoading, setLoading] = useState(false); 
	//const handleClick = () => setLoading(true);
	
  	console.log('query',router.query); 

  	const { dog } = router.query; 
	console.log('dog_id', dog)

	const dogs = JSON.parse(localStorage.getItem('dogs'));
	const thisdog = dogs.result.filter(item => item._id === dog)[0];
	console.log('ddd', dogs)
	console.log('this', thisdog)


	async function handleLogOut() {
	
	  try {
  
		setError("")
		await logOut();
	  } catch {
  
		setError("Failed to Log Out")
  
	  }
	}

	return (
	  <>
		<Head>
		  <title>Create Next App</title>
		  <meta name="description" content="Generated by create next app" />
		  <meta name="viewport" content="width=device-width, initial-scale=1" />
		  <link rel="icon" href="/favicon.ico" />
		</Head>
		<NavComp />
		 <h2> About {thisdog.name} </h2> 
		 <Container className = "d-flex align-items-center justify-content-center" style = {{ minHeight: "100vh" }}>
			<Card style={{ width: '60rem', height:'40rem'}}>
				<Card.Body>
					<Row>
						<Col>
							<Image variant="left" src={"http://localhost:4800/"+ thisdog.image} roundedCircle
							style={{ width: '26rem', height:'30rem'}}/>
								
							<Card.Text variant = "right" >
							<FormControlLabel
								control = {
									<Checkbox
										icon = {<FavoriteBorderIcon />}
										checkedIcon = {<FavoriteIcon />}
									/>
								}
								Label = "Like"
							/>
							<Card.Link href="#">add to favorite</Card.Link>
							<Card.Link href="#">send message</Card.Link>
							<p>{thisdog.message}</p>
							</Card.Text>
						</Col>
						<Col>
							<h3>google map here</h3>
						</Col>
					</Row>	
				</Card.Body>
			</Card>	 	  
        </Container>		
	  </> 
	)
  }
  
  export default withProtected(detail)
  