import Head from 'next/head'
import React from "react";
import { useEffect, useState, useRef } from 'react';
import { Col, Row, Card, Image, Navbar, Nav, Form, Container, Offcanvas, Button } from 'react-bootstrap';
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation';
import 'bootstrap/dist/css/bootstrap.min.css';
import { withProtected } from '../../src/app/routes';
import Overlay from 'react-bootstrap/Overlay';
import Popover from 'react-bootstrap/Popover';
import FormControlLabel from "@mui/material/FormControlLabel";
import FavoriteIcon from "@mui/icons-material/Favorite";
import FavoriteBorderIcon from "@mui/icons-material/FavoriteBorder";
import Checkbox from "@mui/material/Checkbox";
import { GoogleMap, InfoWindowF, MarkerF, useJsApiLoader } from "@react-google-maps/api"

//import { Field, Form, Formik } from "formik";
//import * as Yup from 'yup';

export const DEFAULT_DISTANCE_IN_KM = "1000"

function detail({ auth }) {
	const [ error, setError ] = useState('')
	const router = useRouter()
	const [ dog, setDog ] = useState("")
	const [show, setShow] = useState(false);
 	const [target, setTarget] = useState(null);
  	const ref = useRef(null);
	const { currentUser, logOut } = auth;
	//const [isLoading, setLoading] = useState(false); 
	//const handleClick = () => setLoading(true);
	const searchParams = useSearchParams()
	/*
	const searchParams = useSearchParams()
	//setDog(searchParams.get('dog'))
	const dog = searchParams.get('dog')
  	console.log('dog', dog)
	*/
	useEffect(() => {
		
		setDog(searchParams.get('dog'))
		//const dog = searchParams.get('dog')
		  console.log('dog', dog)
	}),[];
	
	async function handleLogOut() {
	
	  try {
  
		setError("")
		await logOut();
	  } catch {
  
		setError("Failed to Log Out")
  
	  }
	}

	return (
	  <>
		<Head>
		  <title>Create Next App</title>
		  <meta name="description" content="Generated by create next app" />
		  <meta name="viewport" content="width=device-width, initial-scale=1" />
		  <link rel="icon" href="/favicon.ico" />
		</Head>
		{[false].map((expand) => (
		  <Navbar key={expand} bg="dark" variant="dark" expand={expand} className="mb-3">
			<Container fluid>
			<Navbar.Brand href="/">Dog Transportation</Navbar.Brand>
			  <Navbar.Toggle aria-controls={`offcanvasNavbar-expand-${expand}`} />
			  <Navbar.Offcanvas
				id={`offcanvasNavbar-expand-${expand}`}
				aria-labelledby={`offcanvasNavbarLabel-expand-${expand}`}
				placement="end"
			  >
				<Offcanvas.Header closeButton>
				  <Offcanvas.Title id={`offcanvasNavbarLabel-expand-${expand}`}>
				  { currentUser && <div>Hello {currentUser.displayName? currentUser.displayName: currentUser.email}</div> }
				  </Offcanvas.Title>
				</Offcanvas.Header>
				<Offcanvas.Body>
				  <Nav className="justify-content-end flex-grow-1 pe-3">
					<Nav.Link href="/">View my profile</Nav.Link>
					<Nav.Link href="/admin">Upload dogs</Nav.Link>
					<Nav.Link href="/admin">Manage my dogs</Nav.Link>
					<Nav.Link href="../message">My Message</Nav.Link>
					<Nav.Item> 
					  <Nav.Link onClick = { handleLogOut }>Log Out</Nav.Link>
					</Nav.Item>
				  </Nav>
				</Offcanvas.Body>
			  </Navbar.Offcanvas>
			</Container>
		  </Navbar>
		))}
		 <h2> About {dog.name} </h2> 
		 <Container className = "d-flex align-items-center justify-content-center" style = {{ minHeight: "100vh" }}>
			<Card style={{ width: '60rem', height:'40rem'}}>
				<Card.Body>
					<Row>
						<Col>
							<Image variant="left" src="http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fdog_9.77c974bd.jpeg&w=640&q=75" roundedCircle
							style={{ width: '26rem', height:'30rem'}}/>
								
							<Card.Text variant = "right" >
							<FormControlLabel
								control = {
									<Checkbox
										icon = {<FavoriteBorderIcon />}
										checkedIcon = {<FavoriteIcon />}
									/>
								}
								Label = "Like"
							/>
							<Card.Link href="#">add to favorite</Card.Link>
							<Card.Link href="#">send message</Card.Link>
							<p>{dog.message}</p>
							</Card.Text>
						</Col>
						<Col>
							<h3>google map here</h3>
						</Col>
					</Row>	
				</Card.Body>
			</Card>	 	  
        </Container>		
	  </> 
	)
  }
  
  export default withProtected(detail)
  