import Head from 'next/head'
import { useEffect, useState } from 'react';
import { Col, Row, Card, Alert, Navbar, Nav, ListGroup, Container, Offcanvas, Button } from 'react-bootstrap';
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import 'bootstrap/dist/css/bootstrap.min.css';
import { withProtected } from '../../src/app/routes';


function mydogs_admin( {auth} ) {

	const [ error, setError ] = useState('')
	const { currentUser, logOut } = auth;
	const router = useRouter()

	const [isLoading, setLoading] = useState(false);

	const handleClick = () => setLoading(true);
  
	async function handleLogOut() {
	
	  try {
  
		setError("")
		await logOut();
	  } catch {
  
		setError("Failed to Log Out")
  
	  }
	}

	function LoadingButton() {
	  
		useEffect(() => {
		  function simulateNetworkRequest() {
			return new Promise((resolve) => setTimeout(resolve, 2000));
		  }
	  
		  if (isLoading) {
			simulateNetworkRequest().then(() => {
			  setLoading(false);
			});
		  }
		}, [isLoading]);
	  
		
	}  
	return (
	  <>
		<Head>
		  <title>Create Next App</title>
		  <meta name="description" content="Generated by create next app" />
		  <meta name="viewport" content="width=device-width, initial-scale=1" />
		  <link rel="icon" href="/favicon.ico" />
		</Head>
		{[false].map((expand) => (
		  <Navbar key={expand} bg="dark" variant="dark" expand={expand} className="mb-3">
			<Container fluid>
			<Navbar.Brand href="/">Dog Transportation</Navbar.Brand>
			  <Navbar.Toggle aria-controls={`offcanvasNavbar-expand-${expand}`} />
			  <Navbar.Offcanvas
				id={`offcanvasNavbar-expand-${expand}`}
				aria-labelledby={`offcanvasNavbarLabel-expand-${expand}`}
				placement="end"
			  >
				<Offcanvas.Header closeButton>
				  <Offcanvas.Title id={`offcanvasNavbarLabel-expand-${expand}`}>
				  { currentUser && <div>{currentUser?.email}</div> }
				  </Offcanvas.Title>
				</Offcanvas.Header>
				<Offcanvas.Body>
				  <Nav className="justify-content-end flex-grow-1 pe-3">
					<Nav.Link href="/">View my profile</Nav.Link>
					<Nav.Link href="/admin">Upload dogs</Nav.Link>
					<Nav.Link href="/admin">Manage my dogs</Nav.Link>
					<Nav.Link href="../message">My Message</Nav.Link>
					<Nav.Item> 
					  <Nav.Link onClick = { handleLogOut }>Log Out</Nav.Link>
					</Nav.Item>
				  </Nav>
				</Offcanvas.Body>
			  </Navbar.Offcanvas>
			</Container>
		  </Navbar>
		))}
		<Container className = "d-flex align-items-center justify-content-center"
	  style = {{ minHeight: "100vh" }}>
		<div className = "w-100" style = {{ maxWidth: '400px'}}>
			<Card style={{ width: '18rem' }}>
				<Card.Img variant="top" src="holder.js/100px180?text=Image cap" />
				<Card.Body>
					<Card.Title>Card Title</Card.Title>
					<Card.Text>
					Some 
					</Card.Text>
				</Card.Body>
				<ListGroup className="list-group-flush">
					<ListGroup.Item>Cras justo odio</ListGroup.Item>
					<ListGroup.Item>Dapibus ac facilisis in</ListGroup.Item>
				</ListGroup>
				<Card.Body>
					<div className="d-grid gap-2">
						<Button
							href="#"
							variant="primary" size="md"
							disabled={isLoading}
							onClick={!isLoading ? handleClick : null}
						>
							{isLoading ? 'Loading…' : 'Update'} 
						</Button> {'                          '}
						
						<Button
							href="#"
							variant="secondary" size="md"
							disabled={isLoading}
							onClick={!isLoading ? handleClick : null}
						>
							{isLoading ? 'Loading…' : 'Delete'}
						</Button>
					</div>
				</Card.Body>
			</Card>
		</div>
		</Container>  
	  </>
	 
	)
  }
  
  export default withProtected(mydogs_admin)
  