import Head from 'next/head'
import React, { useRef, useState } from 'react'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Form, Button, Card, Alert, Navbar, Container } from 'react-bootstrap'
import Link from 'next/link'
import { updateProfile } from "firebase/auth";
import { withPublic } from '../../src/app/routes';
//import { setDoc, doc } from 'firebase/firestore'


function Register( { auth }) {
	const usernameRef = useRef()
	const emailRef = useRef()
	const passwordlRef = useRef()
	const passwordConfirmRef = useRef()
	const { signUp, currentUser} = auth
	const [ error, setError ] = useState('')
	const [ loading, setLoading ] = useState(false)

	const handleSubmit = async (e) => {
		e.preventDefault()
		
		if (passwordlRef.current.value != passwordConfirmRef.current.value) {
			return setError('PASSWORD DO NOT MATCH')
		}
		try {
			setError('')
			setLoading(true) 
			const userCredential = await signUp(emailRef.current.value, passwordlRef.current.value)
			console.log(userCredential.user) //???? why undefined?
			console.log('you are in!');
			updateProfile(userCredential.user, {
				displayName: usernameRef.current.value, 
			}).then(() => {
				console.log('User Profile Updated Successfully');
				console.log(userCredential.user)
			}).catch((error) => {
				setError(error.message)
			});
		} catch (error) {
			console.log(error)
			if (error.code === 'auth/email-already-in-use') {
				setError("email is already in use try another email")

			} else if (error.code === 'auth/email-already-in-use') {
				setError("passward must be at least 6 characters")

			} else if (error.code === 'auth/invalid-email') {
				setError("Thrown if the email address is not valid")

			} else {
				setError(error.code) 
			}
			
		}
		setLoading(false)	
	}

  return (
	<>
		<Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
          <Navbar bg="dark" variant="dark">
          	<Container>
          		<Navbar.Brand href="/">Dog Transportation</Navbar.Brand>
        	</Container>   
          </Navbar>
        </nav>
	<container className = "d-flex align-items-center justify-content-center"
			style = {{ minHeight: "100vh" }}>
		<div className = "w-100" style = {{ maxWidth: '400px'}}>
			<Card>
				<Card.Body>
					<h2 className = "text-center mb-4">Sign Up</h2> 
					{ error && <Alert variant = "danger"> { error } </Alert> }
					<Form onSubmit={handleSubmit}>
						<Form.Group id = "username">
							<Form.Label> Username </Form.Label>
							<Form.Control type = "username" ref = {usernameRef} required />
						</Form.Group>
						<br />
						<Form.Group id = "email">
							<Form.Label> Email </Form.Label>
							<Form.Control type = "email" ref = {emailRef} required />
						</Form.Group>
						<br />
						<Form.Group id = "password">
							<Form.Label> Password </Form.Label>
							<Form.Control type = "password" ref = {passwordlRef} required />
						</Form.Group>
						<br />
						<Form.Group id = "passwordConfirm">
							<Form.Label> Confirm Password </Form.Label>
							<Form.Control type = "password" ref = {passwordConfirmRef} required />
						</Form.Group>
						<br/ >
						<Button disabled = { loading }  className = "w-100" type = "submit">Sign Up</Button>
					</Form>
					<div className = "w-100 text-center mt-2">
						Already have an account? <Link href="../login/">Log In</Link>
					</div>
				</Card.Body>
			</Card>
		</div>
	</container>
	</>
  )
}
export default withPublic(Register)